title: Yiqian Zhang's Homepage
page-top-title: Yiqian Zhang's Homepage
top-section-bg-text: On the Journey of Long-Termism
home-subtitle: About me
copyright-text: '&copy; yiqianzhang 2025-2035. All Rights Reserved.'

